#!/bin/bash
set -euo pipefail

# Only run in remote (Claude Code on the web) environments
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

INSTALL_DIR="/usr/local/bin"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DISTDIR="${PROJECT_DIR}/.bazel-distdir"

mkdir -p "$DISTDIR"

# Install Bazelisk (provides the `bazel` command)
if ! command -v bazel &>/dev/null; then
  echo "Installing Bazelisk..."
  BAZELISK_VERSION="v1.25.0"
  curl -fsSL "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64" \
    -o "${INSTALL_DIR}/bazel"
  chmod +x "${INSTALL_DIR}/bazel"
  echo "Bazelisk installed successfully"
fi

# Install ibazel (incremental Bazel)
if ! command -v ibazel &>/dev/null; then
  echo "Installing ibazel..."
  IBAZEL_VERSION="v0.25.3"
  curl -fsSL "https://github.com/bazelbuild/bazel-watcher/releases/download/${IBAZEL_VERSION}/ibazel_linux_amd64" \
    -o "${INSTALL_DIR}/ibazel"
  chmod +x "${INSTALL_DIR}/ibazel"
  echo "ibazel installed successfully"
fi

# Create custom Java truststore for Bazel's embedded JDK
# The remote environment uses a TLS-inspecting proxy whose CA is in the system
# trust store but not in Bazel's embedded JDK truststore.
CUSTOM_CACERTS="${DISTDIR}/cacerts"
PROXY_CA="/usr/local/share/ca-certificates/swp-ca-production.crt"

if [ ! -f "$CUSTOM_CACERTS" ] && [ -f "$PROXY_CA" ]; then
  echo "Creating custom truststore with proxy CA..."

  # Prime Bazel installation to get its embedded JDK
  bazel version >/dev/null 2>&1

  BAZEL_INSTALL="$(bazel info install_base 2>/dev/null)"
  BAZEL_CACERTS="${BAZEL_INSTALL}/embedded_tools/jdk/lib/security/cacerts"

  if [ -f "$BAZEL_CACERTS" ]; then
    cp "$BAZEL_CACERTS" "$CUSTOM_CACERTS"
    keytool -importcert -keystore "$CUSTOM_CACERTS" -storepass changeit \
      -noprompt -alias "anthropic-proxy-ca" -file "$PROXY_CA" >/dev/null 2>&1
    echo "Custom truststore created with proxy CA"
  fi
fi

# Generate user.bazelrc for the remote proxy environment
# - Disable Bzlmod (this project uses WORKSPACE, not MODULE.bazel)
# - Use distdir for pre-downloaded dependencies
# - Enable proxy auth for JDK HTTPS tunneling
# - Use custom truststore with proxy's TLS inspection CA
BAZELRC="${PROJECT_DIR}/user.bazelrc"
if [ ! -f "$BAZELRC" ]; then
  cat > "$BAZELRC" << EOF
# Auto-generated by Claude Code session-start hook for remote environments
# This file is gitignored - see .bazelrc try-import
common --noenable_bzlmod
build --distdir=.bazel-distdir
fetch --distdir=.bazel-distdir
query --distdir=.bazel-distdir

# Enable proxy auth for HTTPS tunneling (disabled by default in JDK)
startup --host_jvm_args=-Djdk.http.auth.tunneling.disabledSchemes=
startup --host_jvm_args=-Djdk.http.auth.proxying.disabledSchemes=

# Use custom truststore that includes the proxy's TLS inspection CA
startup --host_jvm_args=-Djavax.net.ssl.trustStore=${DISTDIR}/cacerts
startup --host_jvm_args=-Djavax.net.ssl.trustStorePassword=changeit
EOF
  echo "Created user.bazelrc with proxy-friendly settings"
fi

# Pre-download Bazel WORKSPACE dependencies into distdir
"${PROJECT_DIR}/scripts/bazel_fetch_deps.sh"

echo "Session startup complete: bazel and ibazel are available"
