# .goreleaser.yml
project_name: deleterious
# builds:
#   -
#     main: dummy.go
#     goarch:
#       - amd64
#     binary: deleterious
#     hooks:
#       post: sh build-bazel-release.sh
# archive:
#   replacements:
#     darwin: Darwin
#     linux: Linux
#     windows: Windows
#     # 386: i386
#     # amd64: x86_64
# checksum:
#   name_template: 'checksums.txt'
brews:
  - # Repository to push the tap to.
    github:
      owner: kindlyops
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: support-kindlyops
      email: support@kindlyops.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: |2
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/kindlyops/deleterious"

    # Your app's description.
    # Default is empty.
    description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/deleterious --version"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "deleterious"
