# .goreleaser.yml
project_name: deleterious
builds:
  -
    main: dummy.go
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    binary: deleterious
    hooks:
      post: ./goreleaser-post-hook.sh

checksum:
  name_template: 'checksums.txt'
brews:
  - # Repository to push the tap to.
    tap:
      owner: kindlyops
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: support-kindlyops
      email: support@kindlyops.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: |2
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/kindlyops/deleterious"

    # Your app's description.
    # Default is empty.
    description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/deleterious --version"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "deleterious"

scoop:
  # Template for the url which is determined by the given Token (github or gitlab)
  # Default for github is "https://github.com/<repo_owner>/<repo_name>/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  # Default for gitlab is "https://gitlab.com/<repo_owner>/<repo_name>/uploads/{{ .ArtifactUploadHash }}/{{ .ArtifactName }}"
  # Gitea is not supported yet, but the support coming
  url_template: "http://github.com/kindlyops/deleterious/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: kindlyops
    name: kindlyops-scoop

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: support-kindlyops
    email: support@kindlyops.com

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/kindlyops/deleterious"

  # Your app's description.
  # Default is empty.
  description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

  # Your app's license
  # Default is empty.
  license: Apache2
