# .goreleaser.yml
version: 2
project_name: deleterious

builds:
  - id: darwin-amd64
    main: dummy.go
    goos: [darwin]
    goarch: [amd64]
    binary: deleterious
    hooks:
      post: cp -fv bdist/deleterious-darwin "{{ .Path }}"
  - id: darwin-arm64
    main: dummy.go
    goos: [darwin]
    goarch: [arm64]
    binary: deleterious
    hooks:
      post: cp -fv bdist/deleterious-darwin-m1 "{{ .Path }}"
  - id: linux-amd64
    main: dummy.go
    goos: [linux]
    goarch: [amd64]
    binary: deleterious
    hooks:
      post: cp -fv bdist/deleterious-linux "{{ .Path }}"
  - id: linux-arm64
    main: dummy.go
    goos: [linux]
    goarch: [arm64]
    binary: deleterious
    hooks:
      post: cp -fv bdist/deleterious-linux-arm "{{ .Path }}"
  - id: windows-amd64
    main: dummy.go
    goos: [windows]
    goarch: [amd64]
    binary: deleterious
    hooks:
      post: cp -fv bdist/deleterious-windows.exe "{{ .Path }}"

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
    cmd: syft
    args:
      - "scan"
      - "$artifact"
      - "--output"
      - "spdx-json=$document"

announce:
  discord:
    enabled: true
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }} or brew upgrade {{ .ProjectName }}'
    author: 'GoReleaser'

brews:
  - # Repository to push the tap to.
    repository:
      owner: kindlyops
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: support-kindlyops
      email: support@kindlyops.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: |2
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/kindlyops/deleterious"

    # Your app's description.
    # Default is empty.
    description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/deleterious --version"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "deleterious"

scoops:
  - url_template: "http://github.com/kindlyops/deleterious/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Repository to push the app manifest to.
    repository:
      owner: kindlyops
      name: kindlyops-scoop

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: support-kindlyops
      email: support@kindlyops.com

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/kindlyops/deleterious"

    # Your app's description.
    # Default is empty.
    description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

    # Your app's license
    # Default is empty.
    license: Apache2
