# .goreleaser.yml
project_name: deleterious
builds:
  -
    main: dummy.go
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    binary: deleterious
    hooks:
      post:
        - cmd: ./goreleaser-post-hook.sh
          env:
            - BUILD_TARGET={{ .Target }}
            - ARTIFACT={{ .Path }}


checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: source

announce:
  discord:
    # Whether its enabled or not.
    # Defaults to false.
    enabled: true

    # Message template to use while publishing.
    # Defaults to `{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }}`
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .ReleaseURL }} or brew upgrade {{ .ProjectName }}'

    # Set author of the embed.
    # Defaults to `GoReleaser`
    author: 'GoReleaser'

    # Color code of the embed. You have to use decimal numeral system, not hexadecimal.
    # Defaults to `3888754` - the grey-ish from goreleaser
    color: ''

    # URL to an image to use as the icon for the embed.
    # Defaults to `https://goreleaser.com/static/avatar.png`
    icon_url: ''

brews:
  - # Repository to push the tap to.
    tap:
      owner: kindlyops
      name: homebrew-tap

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: support-kindlyops
      email: support@kindlyops.com

    # Caveats for the user of your binary.
    # Default is empty.
    caveats: |2
      Brought to you by

      _  ___           _ _        ___
      | |/ (_)_ __   __| | |_   _ / _ \\ _ __  ___
      | ' /| | '_ \\ / _| | | | | | | | | '_ \\/ __|
      | . \\| | | | | (_| | | |_| | |_| | |_) \__ \\
      |_|\\_\\_|_| |_|\\__,_|_|\\__, |\\___/| .__/|___/
                            |___/      |_|
      use at your own risk.

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/kindlyops/deleterious"

    # Your app's description.
    # Default is empty.
    description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/deleterious --version"

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    install: |
      bin.install "deleterious"

scoop:
  url_template: "http://github.com/kindlyops/deleterious/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

  # Repository to push the app manifest to.
  bucket:
    owner: kindlyops
    name: kindlyops-scoop

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: kindlymachine[bot]
    email: support@kindlyops.com

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/kindlyops/deleterious"

  # Your app's description.
  # Default is empty.
  description: "Deleterious helps find orphaned resources from AWS CloudFormation DeletionPolicy: Retain"

  # Your app's license
  # Default is empty.
  license: Apache2
