// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	lambda "github.com/aws/aws-sdk-go/service/lambda"
	mock "github.com/stretchr/testify/mock"
)

// LambdaAPI is an autogenerated mock type for the LambdaAPI type
type LambdaAPI struct {
	mock.Mock
}

// GetFunction provides a mock function with given fields: params
func (_m *LambdaAPI) GetFunction(params *lambda.GetFunctionInput) (*lambda.GetFunctionOutput, error) {
	ret := _m.Called(params)

	var r0 *lambda.GetFunctionOutput
	if rf, ok := ret.Get(0).(func(*lambda.GetFunctionInput) *lambda.GetFunctionOutput); ok {
		r0 = rf(params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.GetFunctionOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*lambda.GetFunctionInput) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
