---
name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Environment debug
        run: |
          env
      - name: Install bazelisk
        run: |
          sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Sync Dependencies
        run: bazel run //:vendor
        if: (github.actor == 'dependabot-preview[bot]') || (github.actor == 'renovate[bot]')
      - name: bazel build
        run: bazel run :install
      - name: Test
        run: bazel test //...
      - name: autocommit
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          commit_message: Apply syncdeps changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        if: github.actor == 'dependabot-preview[bot]'
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.17.2
      - name: dry run goreleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: latest
          args: release --snapshot --skip-publish
