---
name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Environment debug
        run: |
          env
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: bazel build
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: run :install
      - name: Test
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: test //...
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13.1
      - name: dry run goreleaser
        uses: goreleaser/goreleaser-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          version: latest
          args: release --snapshot --skip-publish
