---
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install bazelisk
        # yamllint disable rule:line-length
        run: |
          sudo wget -O /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.3.0/bazelisk-linux-amd64
          sudo chmod +x /usr/local/bin/bazel
      # this is tibdex/github-app-token v1.5.1, pinned to the commit SHA for security
      - uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4
        id: generate-token
        with:
          app_id: ${{ secrets.AUTH_FOR_GITHUB_APP_ID }}
          private_key: ${{ secrets.AUTH_FOR_GITHUB_PRIVATE_KEY }}
        if: (github.actor == 'dependabot-preview[bot]') || (github.actor == 'renovate[bot]')
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          # lets see if this works without the custom token
          # token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Sync Dependencies
        run: bazel run //:vendor
        if: (github.actor == 'dependabot-preview[bot]') || (github.actor == 'renovate[bot]')
      - name: autocommit
        uses: stefanzweifel/git-auto-commit-action@v4.13.0
        with:
          commit_message: Apply syncdeps changes
          commit_user_name: kindlymachine[bot]
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        if: (github.actor == 'dependabot-preview[bot]') || (github.actor == 'renovate[bot]')
      - name: bazel build
        run: bazel run :install
      - name: Test
        run: bazel test //...
      - name: Coverage
        run: |
          bazel coverage //...
          echo "coverage_files=$(find bazel-out/ -name 'coverage.dat' -printf '%p, ' | sed 's/, $//')" >> $GITHUB_ENV
      - name: Detected Coverage Files
        run: echo ${{ env.coverage_files }}
      - uses: codecov/codecov-action@v2
        name: codecov upload
        with:
          files: ${{ env.coverage_files }}
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.17.2
      - name: setup-syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
          sh -s -- -b /usr/local/bin v0.32.0
      - name: dry run goreleaser
        uses: goreleaser/goreleaser-action@v2
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          version: latest
          args: release --snapshot --skip-publish
