on:
  push:
    branches:
    - releases/*

name: Create Release
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: goreleaser
      uses: kindlyops/deleterious@master
      env:
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release
