on: push
name: Create Release
jobs:
  is-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: is-tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: goreleaser
      uses: kindlyops/deleterious@master
      env:
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release
