on:
  push:
    branches:
    - master

name: Create Release
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: is-tag
      uses: actions/bin/filter@master
      with:
        args: "tag v*"
    - name: goreleaser
      uses: kindlyops/deleterious@master
      env:
        GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
      with:
        args: release
